# add local binaries to PATH
export PATH=$HOME/.local/bin:$PATH

# zsh local function path
fpath=( "$HOME/.config/zsh/functions" $fpath )

# enable suggestions for commands not found
source /etc/zsh_command_not_found

# Settings
source $HOME/.config/zsh/settings.zsh

# Bootstrap
source $HOME/.config/zsh/bootstrap.zsh

#Aliases
source $HOME/.config/zsh/aliases.zsh

# Plugins
source $HOME/.config/zsh/plugins.zsh

# Dircolors
source $HOME/.config/zsh/dircolors.zsh

# SDKMAN
source $HOME/.config/zsh/sdkman.zsh

# Base 16 shell colors
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Allow local customizations in the .zshrc_local_after file
if [ -f $HOME/.config/zsh-local/zshrc ]; then
    source $HOME/.config/zsh-local/zshrc
fi
