# Plugins
export ZPLUG_HOME=$HOME/.config/zsh/zplug
source $ZPLUG_HOME/init.zsh

zplug "lukechilds/zsh-nvm"
zplug "sindresorhus/pure"
zplug "mafredri/zsh-async"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "rupa/z", use:z.sh
zplug load

# install missing plugins
if ! zplug check --verbose; then
    zplug install
fi

# set environment variables
source $HOME/.config/zsh/env.zsh

# enable suggestions for commands not found
source /etc/zsh_command_not_found

# Settings
source $HOME/.config/zsh/settings.zsh

# Aliases
source $HOME/.config/zsh/aliases.zsh

# Functions
source $HOME/.config/zsh/functions.zsh

# Dircolors
source $HOME/.config/zsh/dircolors.zsh

# SDKMAN
source $HOME/.config/zsh/sdkman.zsh

# NVM auto-use .nvmrc
source $HOME/.config/zsh/nvm.zsh

# Base 16 shell colors
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Allow local customizations in the .zshrc_local_after file
if [ -f $HOME/.config/zsh-local/zshrc ]; then
    source $HOME/.config/zsh-local/zshrc
fi
